/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExclusiveCollectionRouteImport } from './routes/exclusive-collection'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiCheckoutVerifyPaymentRouteImport } from './routes/api/checkout/verify-payment'
import { Route as ApiCheckoutCreateOrderRouteImport } from './routes/api/checkout/create-order'
import { Route as ApiAddressAutocompleteRouteImport } from './routes/api/address/autocomplete'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusiveCollectionRoute = ExclusiveCollectionRouteImport.update({
  id: '/exclusive-collection',
  path: '/exclusive-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutVerifyPaymentRoute =
  ApiCheckoutVerifyPaymentRouteImport.update({
    id: '/api/checkout/verify-payment',
    path: '/api/checkout/verify-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCheckoutCreateOrderRoute = ApiCheckoutCreateOrderRouteImport.update({
  id: '/api/checkout/create-order',
  path: '/api/checkout/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressAutocompleteRoute = ApiAddressAutocompleteRouteImport.update({
  id: '/api/address/autocomplete',
  path: '/api/address/autocomplete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/exclusive-collection': typeof ExclusiveCollectionRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/products': typeof ApiProductsRoute
  '/demo/store': typeof DemoStoreRoute
  '/api/address/autocomplete': typeof ApiAddressAutocompleteRoute
  '/api/checkout/create-order': typeof ApiCheckoutCreateOrderRoute
  '/api/checkout/verify-payment': typeof ApiCheckoutVerifyPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/exclusive-collection': typeof ExclusiveCollectionRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/products': typeof ApiProductsRoute
  '/demo/store': typeof DemoStoreRoute
  '/api/address/autocomplete': typeof ApiAddressAutocompleteRoute
  '/api/checkout/create-order': typeof ApiCheckoutCreateOrderRoute
  '/api/checkout/verify-payment': typeof ApiCheckoutVerifyPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/exclusive-collection': typeof ExclusiveCollectionRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/products': typeof ApiProductsRoute
  '/demo/store': typeof DemoStoreRoute
  '/api/address/autocomplete': typeof ApiAddressAutocompleteRoute
  '/api/checkout/create-order': typeof ApiCheckoutCreateOrderRoute
  '/api/checkout/verify-payment': typeof ApiCheckoutVerifyPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/exclusive-collection'
    | '/login'
    | '/products'
    | '/profile'
    | '/api/contact'
    | '/api/health'
    | '/api/products'
    | '/demo/store'
    | '/api/address/autocomplete'
    | '/api/checkout/create-order'
    | '/api/checkout/verify-payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/exclusive-collection'
    | '/login'
    | '/products'
    | '/profile'
    | '/api/contact'
    | '/api/health'
    | '/api/products'
    | '/demo/store'
    | '/api/address/autocomplete'
    | '/api/checkout/create-order'
    | '/api/checkout/verify-payment'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/exclusive-collection'
    | '/login'
    | '/products'
    | '/profile'
    | '/api/contact'
    | '/api/health'
    | '/api/products'
    | '/demo/store'
    | '/api/address/autocomplete'
    | '/api/checkout/create-order'
    | '/api/checkout/verify-payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ExclusiveCollectionRoute: typeof ExclusiveCollectionRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProductsRoute: typeof ApiProductsRoute
  DemoStoreRoute: typeof DemoStoreRoute
  ApiAddressAutocompleteRoute: typeof ApiAddressAutocompleteRoute
  ApiCheckoutCreateOrderRoute: typeof ApiCheckoutCreateOrderRoute
  ApiCheckoutVerifyPaymentRoute: typeof ApiCheckoutVerifyPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusive-collection': {
      id: '/exclusive-collection'
      path: '/exclusive-collection'
      fullPath: '/exclusive-collection'
      preLoaderRoute: typeof ExclusiveCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/verify-payment': {
      id: '/api/checkout/verify-payment'
      path: '/api/checkout/verify-payment'
      fullPath: '/api/checkout/verify-payment'
      preLoaderRoute: typeof ApiCheckoutVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/create-order': {
      id: '/api/checkout/create-order'
      path: '/api/checkout/create-order'
      fullPath: '/api/checkout/create-order'
      preLoaderRoute: typeof ApiCheckoutCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/autocomplete': {
      id: '/api/address/autocomplete'
      path: '/api/address/autocomplete'
      fullPath: '/api/address/autocomplete'
      preLoaderRoute: typeof ApiAddressAutocompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ExclusiveCollectionRoute: ExclusiveCollectionRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ApiContactRoute: ApiContactRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProductsRoute: ApiProductsRoute,
  DemoStoreRoute: DemoStoreRoute,
  ApiAddressAutocompleteRoute: ApiAddressAutocompleteRoute,
  ApiCheckoutCreateOrderRoute: ApiCheckoutCreateOrderRoute,
  ApiCheckoutVerifyPaymentRoute: ApiCheckoutVerifyPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
